config:
  version-candidate: ./VERSION
  dependencies:
    - graql: [snapshot, release]
    - protocol: [snapshot, release]
    - client-java: release

build:
  correctness:
    build:
      machine: graknlabs-ubuntu-20.04
      type: foreground
      script: |
        sleep 10m
        git clone git@github.com:graknlabs-test/cluster.git

