config:
  version-candidate: ./VERSION
  dependencies:
    common: [snapshot]

build:
  correctness:
    build:
      machine: graknlabs-ubuntu-20.04
      type: foreground
      script: |
        sleep 60m
        git clone git@github.com:graknlabs-test/cluster.git

