build:
  correctness:
    jobs:
      build:
        machine: graknlabs-ubuntu-20.04
        type: foreground
        script: |
          ls -la /etc/
          cat /etc/bazel.bazelrc
          bazel build --config=rbe --announce_rc //...
    execution:
      - build

