build:
  correctness:
    jobs:
      build:
        machine: graknlabs-ubuntu-20.04
        type: foreground
        script: |
          cat /etc/bazel.bazelrc
          sleep 5h
          bazel build --config=rbe --announce_rc //...
    execution:
      - build

